// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyubptogpjfiijqohznb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dWJwdG9ncGpmaWlqcW9oem5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzY2MzIsImV4cCI6MjA2MzQxMjYzMn0.gQWlI27CBzVpS0wkkd6PMTjdcYhEL7LqUlxCPk8NhmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);